server:
  port: 9098

spring:
  application:
    name: request

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registerWithEureka: true


currency:
  oldlivequotes : http://currencies.apps.grandtrunk.net/getlatest/%s/%s
  livequotes: http://export.finam.ru/filename.csv?market=5&em=%s&code=%s&apply=0&df=5&mf=4&yf=2018&from=05.05.2018&dt=5&mt=4&yt=2018&to=05.05.2018&p=8&f=filename&e=.csv&cn=%s&dtf=4&tmf=3&MSOR=1&mstimever=0&sep=1&sep2=2&datf=1&at=1&fsp=1
  quotes: >
    http://export.finam.ru/filename.csv?market=5&
    em=%s& # instrument numeric code
    code=%s&apply=0& # instrument code like AUDCAD
    df=%s& # day as it is
    mf=%s& # month -1 from current
    yf=%s& # year as it is
    from=%s& # date 09.05.2018 - 9 may 2018
    dt=%s& # day as it is
    mt=%s& # month -1 from current
    yt=%s& # year as it is
    to=%s& # date 09.05.2018 - 9 may 2018
    p=%s&f=filename&e=.csv&
    cn=%s& # instrument code like AUDCAD
    dtf=4&tmf=3&MSOR=1&mstimever=0&sep=1&sep2=2&datf=1&at=1&fsp=1

#em - номер финансового инструмента (в нашем случае Газпром - 16842)
#
#df, mf, yf - день, месяц, год даты начиная с которой выдавать котировки
#
#dt, mt, yt - дата по которую выдаются котировки
#
#p - временной интервал (7 означает, что временной интервал 1 час)

# p=2 - minutes
# p=3 - 5 minutes
# p=4 - 10 minutes
# p=5 - 15 minutes
# p=6 - 30 minutes
# p=7 - 1 hour
# p=8 - 1 day
# p=9 - 1 week
# p=10 - 1 months